import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f3f3fe",
        "secondary-container": "#4069f2",
        "on-surface-variant": "#434655",
        "error-container": "#ffdad6",
        "outline": "#737686",
        "on-error": "#ffffff",
        "outline-variant": "#c3c6d7",
        "on-primary-fixed-variant": "#003ea8",
        "secondary-fixed": "#dce1ff",
        "surface-container-highest": "#e1e2ed",
        "surface-variant": "#e1e2ed",
        "on-secondary-container": "#fffbff",
        "on-secondary-fixed-variant": "#0039b5",
        error: "#ba1a1a",
        "on-tertiary-container": "#ffede6",
        "surface-bright": "#faf8ff",
        "surface-container-high": "#e7e7f3",
        "primary-fixed-dim": "#b4c5ff",
        tertiary: "#943700",
        "on-primary-container": "#eeefff",
        "tertiary-container": "#bc4800",
        "on-background": "#191b23",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#0053db",
        "surface-container": "#ededf9",
        "surface-dim": "#d9d9e5",
        "primary-fixed": "#dbe1ff",
        "inverse-primary": "#b4c5ff",
        "inverse-surface": "#2e3039",
        "on-primary-fixed": "#00174b",
        "inverse-on-surface": "#f0f0fb",
        "on-secondary-fixed": "#001551",
        "secondary-fixed-dim": "#b7c4ff",
        surface: "#faf8ff",
        background: "#faf8ff",
        "tertiary-fixed": "#ffdbcd",
        "on-secondary": "#ffffff",
        "on-surface": "#191b23",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        "tertiary-fixed-dim": "#ffb596",
        primary: "#004ac6",
        "on-tertiary-fixed-variant": "#7d2d00",
        secondary: "#1d4ed8",
        "on-tertiary-fixed": "#360f00",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "stack-sm": "8px",
        "stack-md": "16px",
        gutter: "24px",
        "margin-desktop": "64px",
        "section-gap": "120px",
        "container-max": "1280px",
        "stack-lg": "24px",
      },
      fontFamily: {
        "body-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "body-md": ["var(--font-plus-jakarta)", "sans-serif"],
        caption: ["var(--font-plus-jakarta)", "sans-serif"],
        h3: ["var(--font-plus-jakarta)", "sans-serif"],
        "display-lg-mobile": ["var(--font-plus-jakarta)", "sans-serif"],
        h2: ["var(--font-plus-jakarta)", "sans-serif"],
        "display-lg": ["var(--font-plus-jakarta)", "sans-serif"],
        "label-sm": ["var(--font-plus-jakarta)", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "500" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        h3: ["28px", { lineHeight: "1.3", fontWeight: "700" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "800" }],
        h2: ["40px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-sm": ["14px", { lineHeight: "1.4", letterSpacing: "0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require("@tailwindcss/container-queries"),
    require("@tailwindcss/forms"),
  ],
};
export default config;
